// <auto-generated />
using MetaWeather.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetaWeather.Migrations
{
    [DbContext(typeof(LocationContext))]
    partial class LocationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<int>("WOEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LattLong")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LocationType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("WOEID");

                    b.ToTable("locations");
                });
#pragma warning restore 612, 618
        }
    }
}
